// originally generated by 'threeport-sdk create' for API object
// scaffolding but will not be re-generated - intended for modification

package v0

import tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"

type WordpressDefinition struct {
	tpapi_v0.Common         `mapstructure:",squash" swaggerignore:"true"`
	tpapi_v0.Reconciliation `mapstructure:",squash"`
	tpapi_v0.Definition     `mapstructure:",squash"`
	WordpressInstances      []*WordpressInstance `json:"WordpressInstances,omitempty" validate:"optional,association"`
}

type WordpressInstance struct {
	tpapi_v0.Common         `mapstructure:",squash" swaggerignore:"true"`
	tpapi_v0.Reconciliation `mapstructure:",squash"`
	tpapi_v0.Instance       `mapstructure:",squash"`
	WordpressDefinitionID   *uint `gorm:"not null" json:"WordpressDefinitionID,omitempty" query:"wordpressdefinitionid" validate:"required"`
}
