// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package wordpress

import (
	logr "github.com/go-logr/logr"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	v0 "github.com/threeport/wordpress-threeport-extension/pkg/api/v0"
)

// v0WordpressDefinitionCreated performs reconciliation when a v0 workload definition
// has been created.
func v0WordpressDefinitionCreated(
	r *controller.Reconciler,
	wordpressDefinition *v0.WordpressDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0WordpressDefinitionUpdated performs reconciliation when a v0 workload definition
// has been updated.
func v0WordpressDefinitionUpdated(
	r *controller.Reconciler,
	wordpressDefinition *v0.WordpressDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0WordpressDefinitionDeleted performs reconciliation when a v0 workload definition
// has been deleted.
func v0WordpressDefinitionDeleted(
	r *controller.Reconciler,
	wordpressDefinition *v0.WordpressDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
