// generated by 'threeport-sdk gen' - do not edit

package main

import (
	cobra "github.com/spf13/cobra"
	cmd "github.com/threeport/wordpress-threeport-extension/cmd/wordpress/cmd"
)

// Register registers this plugin with tptctl.
func Register(rootCmd *cobra.Command) {
	rootCmd.AddCommand(cmd.WordpressCmd)
}
