// generated by 'threeport-sdk gen' - do not edit

package v0

// WordpressDefinitionConfig contains the config for a wordpress definition.
type WordpressDefinitionConfig struct {
	Name string `json:"Name" validate:"required"`
}

// WordpressInstanceConfig contains the config for a wordpress instance.
type WordpressInstanceConfig struct {
	Name string `json:"Name" validate:"required"`
}
